### ISSUE TITLE
java.lang.NoClassDefFoundError: jakarta/servlet/http/HttpServlet

### ISSUE THREAD

**Issue by DracoDynasty** [devgianlu/PretendYoureXyzzy#64]
Using clean branch master.
Running mvn clean package, which ends successfully.
Running java -jar target/PYX-jar-with-dependencies.jar.

Getting Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/servlet/http/HttpServlet

Here is the full log for those commands: https://pastebin.com/fcYNRqez

From what I've searched and gathered, it shouldn't even try to use jakarta since it's not imported and only javax servlet is being loaded.
Possibly one of the other libraries is too recent and wants to use jakarta ?

I also tried changing some of the dependencies versions, since there were warnings about using "LATEST" on some entries (javax.servlet.jsp-api & jastow, which seemed involved with servlets).
This led to java.lang.ExceptionInInitializerError instead, leaving me unsure if I made progress or just made it worse.

**Comment by devgianlu** [comment]
This fixes the issue: https://github.com/devgianlu/PretendYoureXyzzy/commit/513777ebdd0680ad90cac715c80a63b324e18a86
